### PR TITLE
[#288] Replace Deprecated Usage of `ConflatedBroadcastChannel`

### PR DESCRIPTION
**Pull request by burnoo**
This PR is removing all usages of obsolete `ConflatedBroadcastChannel`:
- in `SdkSynchronizer` and `CompactBlockProcessor` it was replaced with `MutableStateFlow`,
- in `ComputableFlow` with `MutableSharedFlow`

Closes: #288
Closes: #658

> **Note**
This PR slightly changes public API. Exposed `SdkSynchronizer.status` is now `StateFlow` instead of `Flow`. Should it include a bumping version?

*P.S. I have applied for the Android Developer role at Electric Coin, feel free to consider me for this position ;)*

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Manual tests: Did you update the [manual tests](../blob/main/docs/tests) as appropriate? _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
- [ ] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the demo app and try the changes?
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [x] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [x] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after changes and when possible, leave it in a better place._
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [x] Run the app: Did you run the demo app and try the changes? _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Comment by ccjernigan** [comment]
Thank you for this pull request.  We appreciate contributions!  I will review and follow up with any comments as soon as I can.  In the meantime, I'll also start the CI job.  We do currently expect the tests to fail (to be fixed in #619), but compile/detekt/ktlint/lint should all pass.

In terms of the developer role, you'll be in great hands with our team member Savannah who handles those applications!

**Review by ccjernigan — COMMENTED** [review]
On the question about the public API: I think going from Flow to StateFlow is fine as that isn't going to be a breaking change.  StateFlow is still inheriting from Flow.

Overall removing the deprecated Channel API usage is a great improvement.

I think there's a bug introduced, although I haven't narrowed down where exactly.  Some of the parts of the SDK are surprisingly nuanced!

To reproduce, I launched the Demo App and choose Get Balance from the hamburger menu. It will need to download and scan the blockchain to do this, and once on this branch it appears that the download does not start.  The download can be confirmed by the progress on screen, but more quickly it can be noticed in the logcat messages which will be quite verbose when the download happens.

My best guess is that something is happening in the changes with `CompactBlockProcessor`.  Do you want to try to reproduce and see if you can isolate the issue?

**Comment by burnoo** [comment]
You are right - I removed `.onStart { invalidate() }` from `ComputableFlow.flow` while refactoring, and it break download initialization by `FlowPagedListBuilder`.

I fixed it in [953b22b](https://github.com/zcash/zcash-android-wallet-sdk/pull/672/commits/953b22b25659908ac9d250503c537e70328c73aa) additionally adding unit test for covering this case

**Comment by burnoo** [comment]
I found another bug I need to fix :/
> abstract fun [resetReplayCache](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-shared-flow/reset-replay-cache.html)()
...
On a [MutableStateFlow](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-state-flow/index.html), which always contains a single value, this function is not supported, and throws an [UnsupportedOperationException](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unsupported-operation-exception/index.html). To reset a [MutableStateFlow](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-state-flow/index.html) to an initial [value](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-mutable-state-flow/value.html), just update its value.

This is causing `UnsupportedOperationException` in `SdkSynchronizer.stop()`

**Review by ccjernigan — APPROVED** [review]
That's for making this great contribution.  I appreciate the effort that went into it, as well as working through making it high quality!

**Pull request merged**
