### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by mdr0id**
JUST DONT MERGE

### CODE REVIEW

**Comment by gmale** [comment]
sounds like we should merge this? :trollface:

**Comment by gmale** [comment]
Should we close this now that the [tekton PR](https://github.com/zcash/zcash-android-wallet-sdk/pull/137) is merged?

**Comment by 60cd79d6b98a45** [comment]
Hay

**Comment by gmale** [comment]
@mdr0id can this be closed?

**Comment by mdr0id** [comment]
Woops forgot to actually close this from a while ago. Apologies

**Pull request closed without merging**
