### PR TITLE
[#742] Prevent multiple synchronizer instances

### PR DESCRIPTION
**Pull request by ccjernigan**
This prevents two synchronizers from running concurrently for the same network/alias, which can corrupt our data in the filesystem.

The close() call is still asynchronous, because the intended usage in a `callbackFlow` doesn't allow for blocking operations during teardown.  Instead, the blocking happens during synchronizer initialization which allows prior synchronizers to close before a new one starts up.

I also reconfigured the public interface of Synchronizer to remove the stop() call, in favor of making it possible to decouple of the Closeable interface.  For example:

```
val synchronizerFlow: Flow<Synchronizer> = callbackFlow<Synchronizer> {
   val closeableSynchronizer: CloseableSynchronizer = Synchronizer.new(...)

    send(closeableSynchronizer)
    awaitClose {
        closeableSynchronizer.close()
    }
}
```

The SDK version was bumped to 1.11, even though we haven't released 1.10.  This will prevent API changes from breaking Secant which is consuming the snapshots of 1.10.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Manual tests: Did you update the [manual tests](../blob/main/docs/tests) as appropriate? _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
- [x] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the demo app and try the changes?
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [x] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after changes and when possible, leave it in a better place._
- [x] Documentation: Did you review Docs, [README.md](../blob/main/README.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [x] Run the app: Did you run the demo app and try the changes? _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Review by HonzaR — COMMENTED** [review]
These changes are great. The demo-app is now much more stable than before. Thanks! I just pushed a few minor documentation changes and left two notes on the implementation.

While manual testing it, I found these things:

- The blocks sync mechanism is started on the GetAddress screen now too; it wasn't previously. It's probably not a problem. From the implementation it's obvious. The get address demo use-case for this screen just overlaps with another get balance demo now.
- The app is crashing while on send demo after Send button hit. It's maybe not related to these changes, as I saw it previously on FTL for another PR too. But we could file it and link a TODO for it here? It can be reproduced locally, as well as our test_robo_demo_app is impacted.
- And last thing, which I can not reproduce is that I was able to let app freeze with ANR after switching between Balance, List transactions, List UTXOs and Send screens. It happened after the whole sync was done.

**Comment by ccjernigan** [comment]
> These changes are great. The demo-app is now much more stable than before. Thanks! I just pushed a few minor documentation changes and left two notes on the implementation.
> 
> While manual testing it, I found these things:
> 
> * The blocks sync mechanism is started on the GetAddress screen now too; it wasn't previously. It's probably not a problem. From the implementation it's obvious. The get address demo use-case for this screen just overlaps with another get balance demo now.
> * The app is crashing while on send demo after Send button hit. It's maybe not related to these changes, as I saw it previously on FTL for another PR too. But we could file it and link a TODO for it here? It can be reproduced locally, as well as our test_robo_demo_app is impacted.
> * And last thing, which I can not reproduce is that I was able to let app freeze with ANR after switching between Balance, List transactions, List UTXOs and Send screens. It happened after the whole sync was done.

Synchronizer will always sync now.  We can consider whether we need either APIs to get addresses without syncing OR a way to pause syncing separately from synchronizer construction. But i don’t currently know a good use case for that.

The Send crash is that it doesn’t validate the address field, so bad input will crash the SDK.  This is a pre-existing issue.  I think it will get fixed as part of the Compose re-write.

There are probably still some ANRs in the demo app, since it never worried about blocking the UI thread.  Can you try pulling the trace?  https://developer.android.com/topic/performance/vitals/anr#trace-files

**Comment by HonzaR** [comment]
> There are probably still some ANRs in the demo app, since it never worried about blocking the UI thread. Can you try pulling the trace? https://developer.android.com/topic/performance/vitals/anr#trace-files

Unfortunately, I'm not able to load them, as it happened on my Pixel6

**Review by HonzaR — APPROVED** [review]
I found that the benchmarking wasn't working well. The sync blocks test did not measure all Synchronizer statuses correctly. I checked it above main branch code and it worked well. So I dived into the changes and found that we missed to keep the benchmark test injected birthday height. It seems alright, after fixing it.

Then I could approach to compare benchmark results after these PR updates.

These are previous test results:
```
Starting 3 tests on Pixel 6 - 13

StartupBenchmark_appStartup
timeToInitialDisplayMs   min 388.8,   median 410.9,   max 423.0
Traces: Iteration 0 1 2 3 4

StartupBenchmark_tracesSdkStartup
ADDRESS_SCREENMs   min 784.1,   median 900.4,   max 926.9
SAPLING_ADDRESSMs   min   2.4,   median   4.3,   max   5.9
TRANSPARENT_ADDRESSMs   min   1.7,   median   2.6,   max   6.0
UNIFIED_ADDRESSMs   min   1.5,   median   2.2,   max   2.8
Traces: Iteration 0 1 2 3 4

SyncBlockchainBenchmark_tracesSyncBlockchain
BALANCE_SCREENMs   min 46,042.2,   median 46,233.0,   max 46,462.2
BLOCKCHAIN_SYNCMs   min 45,393.5,   median 45,578.3,   max 45,830.3
DOWNLOADMs   min 34,951.3,   median 35,763.0,   max 35,870.6
SCANMs   min  9,536.7,   median  9,846.5,   max 10,501.8
VALIDATIONMs   min     93.1,   median    112.5,   max    124.3
Traces: Iteration 0 1 2

BUILD SUCCESSFUL in 4m 18s
```

And these are the new ones from this PR:
```
Starting 3 tests on Pixel 6 - 13

StartupBenchmark_appStartup
timeToInitialDisplayMs   min 259,4,   median 265,8,   max 312,7
Traces: Iteration 0 1 2 3 4

StartupBenchmark_tracesSdkStartup
ADDRESS_SCREENMs   min 958,7,   median 972,2,   max 981,5
SAPLING_ADDRESSMs   min   2,0,   median   2,3,   max   6,3
TRANSPARENT_ADDRESSMs   min   1,2,   median   2,1,   max   3,2
UNIFIED_ADDRESSMs   min   1,8,   median   2,1,   max   3,2
Traces: Iteration 0 1 2 3 4

SyncBlockchainBenchmark_tracesSyncBlockchain
BALANCE_SCREENMs   min 67 016,6,   median 67 859,8,   max 71 026,5
BLOCKCHAIN_SYNCMs   min 66 240,6,   median 67 001,5,   max 70 187,5
DOWNLOADMs   min 55 489,0,   median 56 233,1,   max 60 132,9
SCANMs   min  9 964,0,   median 10 517,3,   max 10 670,7
VALIDATIONMs   min     90,1,   median     96,6,   max    233,6
Traces: Iteration 0 1 2

BUILD SUCCESSFUL in 4m 51s
```
So I can see a significant slowness in download phase, but it could be related just to the mainnet current condition. What do you think?

**Pull request merged**
